name = "auth0-custom-domain-hono"
main = "src/index.ts"
compatibility_date = "2025-07-20"

workers_dev = false

routes = [
    { pattern = "cf-hono.smcd.authlab.work", custom_domain = true }
]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
